'use strict';
const $=id=>document.getElementById(id), charts=new Map();
let payload=null,selected=1001,horizon=24,view='overview',lastLoad=null;
const fmt=(v,n=1)=>Number.isFinite(Number(v))&&v!==null?Number(v).toLocaleString('zh-CN',{maximumFractionDigits:n}):'—';
const pct=v=>v===null||v===undefined?'—':fmt(v*100,1)+'%';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={hour:'上一小时基线',day:'昨日同小时基线',week:'上周同小时基线','8week':'8 周同期均值',global:'全局 GBT',station:'分站 GBT',als:'ALS',user_history:'用户历史偏好',global_popular:'全局热门时段',user_mean:'用户历史均值',slot_mean:'时段均值'};
const colors=['#21855b','#cd9e4b','#77ab96','#91b7c6','#687eaa'];
function chart(id,option){let c=charts.get(id);if(!c){c=echarts.init($(id));charts.set(id,c)}c.setOption({color:colors,animationDuration:350,textStyle:{fontFamily:'Microsoft YaHei,sans-serif',color:'#557265'},...option},true);c.resize()}
function kpis(id,items){$(id).innerHTML=items.map(([label,value,note],i)=>`<div class="kpi ${i===0?'primary':''}"><small>${esc(label)}</small><strong>${esc(value)}</strong><small>${esc(note||'')}</small></div>`).join('')}
function table(id,headers,rows){$(id).innerHTML=`<table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function axes(labels){return {tooltip:{trigger:'axis'},grid:{left:48,right:20,top:30,bottom:35},xAxis:{type:'category',data:labels,axisLine:{lineStyle:{color:'#dce6df'}},axisLabel:{color:'#71847b'}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#edf2ee'}}}}}
function overview(){const d=payload.overview.data,o=d.operation_overview[0];kpis('overview-kpis',[
['结算电量',fmt(o.energy_kwh)+' kWh','按会话真实时间分摊'],['数据日收入','¥ '+fmt(o.revenue),'按窗口分摊费用'],['数据日订单',fmt(o.orders,0),'按会话开始时间统计'],['设备利用率',pct(o.utilization),'15 分钟状态平均'],['故障桩时率',pct(o.fault_rate),'修正后的设备状态'],['累计用户',fmt(o.total_users,0),'当日活跃 '+fmt(o.active_users,0)]]);
 table('ranking',['站点','健康度','电量 kWh'],payload['station-ranking'].data.slice(0,10).map(x=>[x.station_name,fmt(x.health),fmt(x.energy_kwh)]));
 const district=d.district_map.sort((a,b)=>b.energy_kwh-a.energy_kwh);chart('district-chart',{...axes(district.map(x=>x.district)),xAxis:{type:'value'},yAxis:{type:'category',inverse:true,data:district.map(x=>x.district),axisLabel:{fontSize:10}},grid:{left:62,right:22,top:5,bottom:25},series:[{type:'bar',data:district.map(x=>x.energy_kwh),barMaxWidth:14,itemStyle:{borderRadius:[0,5,5,0]}}]});
 const trend=d.operation_trend.slice(-30);chart('trend-chart',{...axes(trend.map(x=>String(x.dt).slice(5,10))),series:[{name:'结算电量',type:'line',smooth:true,symbol:'none',areaStyle:{opacity:.13},data:trend.map(x=>x.energy_kwh)}]});
 const device=d.device_status?.[0];chart('tariff-chart',{tooltip:{trigger:'item'},legend:{bottom:0,textStyle:{fontSize:10}},series:[{type:'pie',radius:['45%','72%'],center:['50%','43%'],label:{show:false},data:device?[{name:'空闲',value:device.idle},{name:'充电中',value:device.busy},{name:'故障',value:device.fault}]:d.tariff_contribution.map(x=>({name:x.band,value:Math.round(x.energy_kwh)}))}]});$('overview-alerts').textContent=d.realtime_alert.slice(0,2).map(x=>x.station_name+' · 排队峰值 '+fmt(x.peak_queue)).join(' / ');}
function forecast(){const d=payload['load-forecast'].data.find(x=>x.station_id===selected)||payload['load-forecast'].data[0];selected=d.station_id;$('station-select').value=String(selected);const points=d.points.slice(0,horizon),m=d.metrics;const total=points.reduce((a,p)=>a+p.load_kwh,0);kpis('forecast-kpis',[
[`${horizon} 小时预测电量`,fmt(total)+' kWh',names[d.model]],['测试集 MAE',fmt(m.mae)+' kWh','每日起点递归 24 小时'],['测试集 RMSE',fmt(m.rmse)+' kWh',fmt(m.n,0)+' 个测试小时'],['测试集 WMAPE',pct(m.wmape),'零负荷安全指标'],['相对基线改善',pct(d.improvement),names[d.baseline]],['峰值预警',points.filter(p=>p.alert==='peak').length+' 小时','预测超过 85% 容量阈值']]);
 $('forecast-title').textContent=d.name;
 $('forecast-meta').innerHTML=`<b>${esc(names[d.model])}</b> · 版本 ${esc(d.model_version)}<br>预测起点 ${esc(d.origin)}　训练区间 ${esc(d.train_start)} 至 ${esc(d.train_end)}`;
 const history=d.history.slice(-6), labels=[...history.map(x=>x.time.slice(5,16).replace('T',' ')),...points.map(x=>x.time.slice(5,16).replace('T',' '))],empty=history.map(()=>null);
 chart('forecast-chart',{...axes(labels),legend:{top:0,itemWidth:15,textStyle:{fontSize:10},data:['历史实际','预测','经验区间上界','85% 容量阈值']},grid:{left:50,right:20,top:40,bottom:45},series:[
 {name:'历史实际',type:'line',data:[...history.map(x=>x.load_kwh),...points.map(()=>null)],symbolSize:4},
 {name:'预测',type:'line',data:[...empty,...points.map(x=>x.load_kwh)],symbolSize:5,itemStyle:{color:'#c18a32'},lineStyle:{width:3}},
 {name:'区间下界',type:'line',data:[...empty,...points.map(x=>x.lower_kwh)],stack:'band',symbol:'none',lineStyle:{opacity:0},itemStyle:{opacity:0},tooltip:{show:false}},
 {name:'经验区间上界',type:'line',data:[...empty,...points.map(x=>x.upper_kwh-x.lower_kwh)],stack:'band',symbol:'none',lineStyle:{opacity:0},areaStyle:{color:'#72b891',opacity:.24},tooltip:{valueFormatter:()=> '详见每小时区间表'}},
 {name:'85% 容量阈值',type:'line',data:labels.map(()=>points[0].capacity_kwh===null?null:points[0].capacity_kwh*.85),lineStyle:{type:'dashed',color:'#bd6064'},itemStyle:{color:'#bd6064'},symbol:'none'}]});
 table('forecast-table',['时间','电量','区间','空闲','排队','预警'],points.map(x=>[x.time.slice(11,16),fmt(x.load_kwh),fmt(x.lower_kwh)+'–'+fmt(x.upper_kwh),x.idle,x.queue,x.alert==='peak'?'峰值':'正常']));
 const peak=points.reduce((a,b)=>a.load_kwh>b.load_kwh?a:b);$('forecast-advice').textContent=`当前窗口峰值 ${peak.time.slice(11,16)}，预计 ${fmt(peak.load_kwh)} kWh。${points.some(x=>x.alert==='peak')?'建议提前检查可用设备，并引导错峰充电。':'当前窗口未触发容量阈值预警。'} 空闲和排队为功率换算估计。`;
 const importance=Object.entries(d.feature_importance||{}).sort((a,b)=>b[1]-a[1]).slice(0,6);
 $('feature-explanation').innerHTML=`${esc(d.exogenous)}<br>${d.model==='station'?'分站 GBT 重要特征：'+importance.map(([k,v])=>esc(k)+' '+pct(v)).join(' · '):'当前采用 '+esc(names[d.model])+'。'}<br>${esc(d.interval_method)}`;
 $('baseline-explanation').textContent=`验证集决定发布模型。最佳基线 ${names[d.baseline]} 的测试 MAE 为 ${fmt(d.baseline_metrics.mae)} kWh。${d.test_degraded?'测试集出现退化，已在健康页标记，未用测试集重新挑选模型。':'完整保留四个朴素基线和模型评估。'} 当前 ${horizon} 小时开关只截取同一条 24 点序列。`;}
function users(){const d=payload['user-demand'].data,t=d.evaluation.test.time[d.time_model],e=d.evaluation.test.energy[d.energy_model];kpis('user-kpis',[
['覆盖用户',fmt(d.user_count,0),'全部输出，含冷启动回退'],['时段 HitRate@3',pct(t.hit_rate_3),names[d.time_model]],['时段 MRR',fmt(t.mrr,3),'每用户最后一次为测试'],['电量 MAE',fmt(e.mae)+' kWh',names[d.energy_model]],['预计平均电量',fmt(d.mean_next_kwh)+' kWh','群体统计'],['服务覆盖率',pct(d.coverage),'新用户只展示群体分布']]);
 chart('heatmap-chart',{tooltip:{position:'top',formatter:p=>`周${['一','二','三','四','五','六','日'][p.value[1]]} ${p.value[0]} 时<br>训练会话 ${p.value[2]} 次`},grid:{left:45,right:15,top:15,bottom:60},xAxis:{type:'category',data:Array.from({length:24},(_,i)=>i+'时'),splitArea:{show:true},axisLabel:{fontSize:10}},yAxis:{type:'category',data:['周一','周二','周三','周四','周五','周六','周日'],splitArea:{show:true}},visualMap:{min:0,max:Math.max(...d.heatmap.map(x=>x[2])),calculable:true,orient:'horizontal',left:'center',bottom:0,inRange:{color:['#edf5ed','#8bbfa0','#157d54']}},series:[{type:'heatmap',data:d.heatmap,itemStyle:{borderWidth:2,borderColor:'#fff'}}]});
 chart('energy-chart',{...axes(d.energy_distribution.map(x=>fmt(x.from,0)+'–'+fmt(x.to,0))),series:[{name:'用户数',type:'bar',data:d.energy_distribution.map(x=>x.count),itemStyle:{borderRadius:[5,5,0,0]}}]});
 table('user-evaluation',['任务 / 模型','HitRate@1','HitRate@3','MRR','MAE / kWh'],[...Object.entries(d.evaluation.test.time).map(([k,m])=>['时段 / '+names[k],pct(m.hit_rate_1),pct(m.hit_rate_3),fmt(m.mrr,3),'—']),...Object.entries(d.evaluation.test.energy).map(([k,m])=>['电量 / '+names[k],'—','—','—',fmt(m.mae)])]);
 $('user-fallback').textContent=`${d.fallback}。冷启动示例：预计电量 ${fmt(d.cold_start_example.next_kwh)} kWh（${d.cold_start_example.basis}，非个性化）。版本 ${d.version}。每个用户倒数第二次会话用于验证，最后一次用于测试。`;}
function health(){const d=payload['pipeline-health'].data,q=payload['data-quality'].data,f=payload['load-forecast'].data;kpis('health-kpis',[
['源数据行数',fmt(d.source_manifest.reduce((a,x)=>a+x.rows,0),0),'5 张表 · 校验和可追溯'],['质量规则',fmt(d.quality_rule_count,0),'ERROR / WARN / INFO'],['错误规则命中',fmt(d.error_rule_hits,0),'错误行隔离，不静默丢弃'],['预测站点',fmt(d.model_count,0),'每站未来 24 点'],['基线回退',fmt(d.baseline_fallbacks,0),'诚实展示最佳验证方案'],['测试退化站点',fmt(d.test_degraded_count,0),'相对验证选出的最佳基线']]);
 $('storage-label').textContent=d.storage.startsWith('hdfs:')?'HDFS 存储':'本地 Spark 验证环境';$('layers').innerHTML=Object.entries(d.layers).map(([k,v])=>`<div class="layer"><b>${esc(k.toUpperCase())}</b><small>${esc(v)}</small></div>`).join('');
 table('quality-table',['表 / 规则','等级','异常数','处置'],q.map(x=>[x.table_name+' / '+x.rule_id,x.severity,fmt(x.failed_count,0),x.action]));
 table('pipeline-table',['作业','状态','Application ID'],d.stages.map(x=>[x.stage,x.status,x.application_id]));
 table('model-table',['站点','发布模型','测试 MAE','基线 MAE','改善','状态','模型版本'],f.map(x=>[x.name,names[x.model],fmt(x.metrics.mae),fmt(x.baseline_metrics.mae),pct(x.improvement),x.test_degraded?'测试退化':x.needs_optimization?'基线回退':'已发布',x.model_version]));}
function render(){if(!payload)return;$('empty').classList.add('hidden');document.querySelectorAll('.view').forEach(s=>s.classList.toggle('active',s.id==='view-'+view));({overview,forecast,users,health})[view]();}
function switchView(name){view=name;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view)});document.querySelectorAll('.view').forEach(s=>s.classList.toggle('active',s.id==='view-'+view));render();}
function status(message,kind='warn'){$('status').className='status '+kind;$('status-text').textContent=message;}
async function getJSON(url){const res=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!res.ok)throw new Error('HTTP '+res.status);return res.json()}
async function load(){try{if(location.protocol==='file:')throw new Error('请通过 HTTP 打开大屏');let current,staticFallback=false;try{current=await getJSON('data/current.json')}catch(_){staticFallback=true;current={files:Object.fromEntries(['overview','stations','station-ranking','load-forecast','user-demand','data-quality','pipeline-health'].map(k=>[k,k+'.json']))}}const entries=await Promise.all(Object.entries(current.files).map(async([k,p])=>[k,await getJSON('data/'+p)]));const candidate=Object.fromEntries(entries);if(staticFallback)current.runId=candidate.overview?.runId;for(const key of ['overview','stations','station-ranking','load-forecast','user-demand','data-quality','pipeline-health']){const v=candidate[key];if(!v||v.schemaVersion!=='1.0'||v.runId!==current.runId||v.dataNature!=='模拟数据')throw new Error('数据契约或运行编号不一致')}
 payload=candidate;lastLoad=Date.now();const meta=payload.overview;$('data-time').textContent='数据截止 '+meta.dataTime;$('generation').textContent='生成 '+meta.generatedAt+' · 运行 '+meta.runId;
 const select=$('station-select');select.innerHTML=payload['load-forecast'].data.map(x=>`<option value="${x.station_id}">${esc(x.name)}</option>`).join('');
 const age=Date.now()-Date.parse(meta.generatedAt);status(age>86400000?'数据已延迟：保留最近一次成功结果。':'历史模拟数据回放 · 最近一次计算成功',age>86400000?'warn':'');
 if(staticFallback)status('已降级：使用随工程保存的静态结果，请核对数据与生成日期。','warn');
 if(payload['pipeline-health'].data.status!=='SUCCESS')status('链路已降级：展示最近一次可用结果。','warn');
 try{const attempt=await getJSON('data/latest-attempt.json');if(attempt.status==='FAILED'&&Date.parse(attempt.generatedAt)>Date.parse(meta.generatedAt))status('最新任务失败：'+attempt.stage+'；保留上次成功结果。','error')}catch(_){}
 render();}catch(e){status((payload?'已降级，保留已加载结果：':'数据暂不可用：')+e.message,'error');if(!payload){$('empty').classList.remove('hidden');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));}}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$('station-select').addEventListener('change',e=>{selected=Number(e.target.value);forecast()});document.querySelectorAll('[data-h]').forEach(b=>b.addEventListener('click',()=>{horizon=Number(b.dataset.h);document.querySelectorAll('[data-h]').forEach(x=>x.classList.toggle('active',x===b));if(payload)forecast()}));$('refresh').addEventListener('click',load);window.addEventListener('resize',()=>charts.forEach(c=>c.resize()));setInterval(()=>{if(lastLoad&&Date.now()-lastLoad>300000)status('连接已延迟，保留最近一次成功结果。','warn')},60000);setInterval(load,120000);load();
