'use strict';
const $=id=>document.getElementById(id), charts=new Map();
let payload=null,selected=1001,horizon=24,view='overview',lastLoad=null;
const fmt=(v,n=1)=>Number.isFinite(Number(v))&&v!==null?Number(v).toLocaleString('zh-CN',{maximumFractionDigits:n}):'—';
const pct=v=>v===null||v===undefined?'—':fmt(v*100,1)+'%';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={hour:'上一小时基线',day:'昨日同小时基线',week:'上周同小时基线','8week':'可用周同期基线',global:'全局 GBT',station:'分站 GBT',shared_gbt:'全站共享 GBT',residual_cnn:'CNN 残差模型',als:'ALS',hybrid:'混合模型',user_history:'用户历史偏好',global_popular:'全局热门时段',user_mean:'用户历史均值',slot_mean:'时段均值'};
const colors=['#21855b','#cd9e4b','#77ab96','#91b7c6','#687eaa'];
function startParticles(){const canvas=$('particle-canvas'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,bands=[{a:.02,b:.30,c:'89,183,204'},{a:.35,b:.63,c:'204,168,88'},{a:.68,b:.98,c:'66,189,140'}],particles=[];let width=0,height=0,dpr=1,seed=20260915;const random=()=>((seed=Math.imul(seed^seed>>>15,1|seed))^(seed+Math.imul(seed^seed>>>7,61|seed)))>>>0,unit=()=>random()/4294967296;function resize(){dpr=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);particles.length=0;bands.forEach((band,group)=>{for(let i=0;i<120;i++)particles.push({group,x:width*(band.a+unit()*(band.b-band.a)),y:unit()*height,vx:(unit()-.5)*.10,vy:(unit()-.5)*.10,r:.45+unit()*1.15,phase:unit()*Math.PI*2})})}function frame(time){ctx.clearRect(0,0,width,height);for(const p of particles){const band=bands[p.group];if(!reduced){p.vx+=(unit()-.5)*.004;p.vy+=(unit()-.5)*.004;p.vx=Math.max(-.13,Math.min(.13,p.vx));p.vy=Math.max(-.13,Math.min(.13,p.vy));p.x+=p.vx+Math.sin(time*.00018+p.phase)*.018;p.y+=p.vy+Math.cos(time*.00016+p.phase)*.018;const min=width*band.a,max=width*band.b;if(p.x<min||p.x>max){p.vx*=-1;p.x=Math.max(min,Math.min(max,p.x))}if(p.y<0||p.y>height){p.vy*=-1;p.y=Math.max(0,Math.min(height,p.y))}}ctx.beginPath();ctx.fillStyle=`rgba(${band.c},${.22+.16*Math.sin(time*.00035+p.phase)})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}if(!reduced)requestAnimationFrame(frame)}addEventListener('resize',resize,{passive:true});resize();requestAnimationFrame(frame)}
function chart(id,option){let c=charts.get(id);if(!c){c=echarts.init($(id));charts.set(id,c)}c.setOption({color:colors,animationDuration:350,textStyle:{fontFamily:'Microsoft YaHei,sans-serif',color:'#557265'},...option},true);c.resize()}
function kpis(id,items){$(id).innerHTML=items.map(([label,value,note],i)=>`<div class="kpi ${i===0?'primary':''}"><small>${esc(label)}</small><strong>${esc(value)}</strong><small>${esc(note||'')}</small></div>`).join('')}
function table(id,headers,rows){$(id).innerHTML=`<table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function axes(labels){return {tooltip:{trigger:'axis'},grid:{left:48,right:20,top:30,bottom:35},xAxis:{type:'category',data:labels,axisLine:{lineStyle:{color:'#dce6df'}},axisLabel:{color:'#71847b'}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#edf2ee'}}}}}
function overview(){const d=payload.overview.data,o=d.operation_overview[0],hybrid=payload.overview.dataNature==='真实数据+模拟补齐';kpis('overview-kpis',[
['结算电量',fmt(o.energy_kwh)+' kWh','真实订单 · 会话时长分摊'],['数据日收入','¥ '+fmt(o.revenue),'真实订单费用'],['数据日订单',fmt(o.orders,0),'真实会话开始时间'],['设备利用率',pct(o.utilization),'真实时长/枪数派生'],['故障桩时率',pct(o.fault_rate),hybrid?'模拟补齐':'设备状态'],['累计用户',fmt(o.total_users,0),hybrid?'模拟补齐 · 活跃 '+fmt(o.active_users,0):'活跃 '+fmt(o.active_users,0)]]);
 $('ranking-title').textContent='站点预测健康排行';$('ranking-legend').textContent=hybrid?'真实运营 + 模型派生 + 故障模拟补齐':'综合故障 / 排队 / 利用率';$('district-title').textContent='充电场景负荷';
 table('ranking',['站点','健康度','电量 kWh'],payload['station-ranking'].data.slice(0,10).map(x=>[x.station_name,fmt(x.health),fmt(x.energy_kwh)]));
 const district=d.district_map.sort((a,b)=>b.energy_kwh-a.energy_kwh);chart('district-chart',{...axes(district.map(x=>x.district)),xAxis:{type:'value'},yAxis:{type:'category',inverse:true,data:district.map(x=>x.district),axisLabel:{fontSize:10}},grid:{left:62,right:22,top:5,bottom:25},series:[{type:'bar',data:district.map(x=>x.energy_kwh),barMaxWidth:14,itemStyle:{borderRadius:[0,5,5,0]}}]});
 const trend=d.operation_trend.slice(-30);chart('trend-chart',{...axes(trend.map(x=>String(x.dt).slice(5,10))),series:[{name:'结算电量',type:'line',smooth:true,symbol:'none',areaStyle:{opacity:.13},data:trend.map(x=>x.energy_kwh)}]});
 const device=d.device_status?.[0];chart('device-chart',{tooltip:{trigger:'item'},legend:{bottom:0,textStyle:{fontSize:9}},series:[{type:'pie',radius:['42%','70%'],center:['50%','42%'],label:{show:false},data:device?[{name:'空闲',value:device.idle},{name:'充电中',value:device.busy},{name:'故障',value:device.fault}]:[]}]});
 chart('tariff-chart',{tooltip:{trigger:'item',valueFormatter:v=>fmt(v)+' kWh'},legend:{bottom:0,textStyle:{fontSize:9}},series:[{type:'pie',radius:['42%','70%'],center:['50%','42%'],label:{show:false},data:d.tariff_contribution.map(x=>({name:x.band.split('(')[0],value:Math.round(x.energy_kwh)}))}]});
 const weighted=rows=>rows.reduce((a,x)=>a+x.avg_kwh*x.hours,0)/Math.max(1,rows.reduce((a,x)=>a+x.hours,0)),holiday=weighted(d.load_factors.filter(x=>x.holiday===1)),weekday=weighted(d.load_factors.filter(x=>x.holiday===0)),gap=d.load_discrepancy?.[0];
 const telemetry=gap?.comparable?`结算与遥测口径偏差 ${pct(gap.relative_difference)}`:(gap?.reason||'遥测累计字段不可用');
 $('overview-alerts').textContent=`预测排队关注 ${d.realtime_alert.length} 站 · 周末平均订单电量较工作日 ${holiday>=weekday?'高':'低'} ${pct(Math.abs(holiday/weekday-1))} · ${telemetry}`;}
function projectedPoints(d,h){const raw=d.points.slice(0,h),direct=d.direct_horizons?.[String(h)],rawTotal=raw.reduce((a,p)=>a+p.load_kwh,0),target=direct?.prediction_kwh??rawTotal,scale=rawTotal>0?target/rawTotal:0;return raw.map(p=>{const load=rawTotal>0?p.load_kwh*scale:target/h,lower=rawTotal>0?p.lower_kwh*scale:Math.max(0,load),upper=rawTotal>0?p.upper_kwh*scale:load,capacity=p.capacity_kwh,power=capacity?capacity/d.device_count:null,busy=power?Math.ceil(load/power):null;return {...p,load_kwh:load,lower_kwh:Math.min(load,lower),upper_kwh:Math.max(load,upper),idle:busy===null?null:Math.max(0,d.device_count-busy),queue:busy===null?null:Math.max(0,busy-d.device_count),alert:capacity&&(load>capacity*.85||busy>d.device_count)?'peak':'normal'}})}
function forecast(){const d=payload['load-forecast'].data.find(x=>x.station_id===selected)||payload['load-forecast'].data[0];selected=d.station_id;$('station-select').value=String(selected);const direct=d.direct_horizons?.[String(horizon)],points=projectedPoints(d,horizon),m=direct?.metrics||d.metrics;const total=direct?.prediction_kwh??points.reduce((a,p)=>a+p.load_kwh,0),model=direct?.model||d.model,improvement=direct?.improvement??d.improvement;kpis('forecast-kpis',[
[`${horizon} 小时预测电量`,fmt(total)+' kWh',direct?`${names[model]} · H${horizon} 直接预测`:names[model]],['测试集 MAE',fmt(m.mae)+' kWh',direct?`H${horizon} 累计电量直接回测`:'每日起点递归 24 小时'],['测试集 RMSE',fmt(m.rmse)+' kWh',fmt(m.n,0)+' 个测试窗口'],['测试集 WMAPE',pct(m.wmape),'零负荷安全指标'],['相对基线改善',pct(improvement),'可用周同期累计基线'],['峰值预警',points.filter(p=>p.alert==='peak').length+' 小时','真实枪数/功率 + 预测负荷']]);
 $('forecast-title').textContent=d.name;
 $('forecast-meta').innerHTML=`<b>${esc(names[model])}</b> · 版本 ${esc(direct?.candidate_version||d.model_version)} · ${direct?esc(direct.selection||`H${horizon} 直接模型竞争`):'逐小时递归模型'}<br>预测起点 ${esc(d.origin)}　训练区间 ${esc(d.train_start)} 至 ${esc(d.train_end)}`;
 const history=d.history.slice(-6), labels=[...history.map(x=>x.time.slice(5,16).replace('T',' ')),...points.map(x=>x.time.slice(5,16).replace('T',' '))],empty=history.map(()=>null),baseAxes=axes(labels),threshold=points[0].capacity_kwh===null?null:points[0].capacity_kwh*.85,loadMax=Math.max(1,...history.map(x=>x.load_kwh),...points.map(x=>x.upper_kwh));
 chart('forecast-chart',{...baseAxes,yAxis:[{...baseAxes.yAxis,min:0,max:Math.ceil(loadMax*1.12)},{type:'value',show:false,min:0,max:threshold?threshold*1.08:loadMax}],legend:{top:0,itemWidth:15,textStyle:{fontSize:10},data:['历史实际','预测','经验区间上界','85% 容量阈值']},grid:{left:50,right:20,top:40,bottom:45},series:[
 {name:'历史实际',type:'line',data:[...history.map(x=>x.load_kwh),...points.map(()=>null)],symbolSize:4},
 {name:'预测',type:'line',data:[...empty,...points.map(x=>x.load_kwh)],symbolSize:5,itemStyle:{color:'#c18a32'},lineStyle:{width:3}},
 {name:'区间下界',type:'line',data:[...empty,...points.map(x=>x.lower_kwh)],stack:'band',symbol:'none',lineStyle:{opacity:0},itemStyle:{opacity:0},tooltip:{show:false}},
 {name:'经验区间上界',type:'line',data:[...empty,...points.map(x=>x.upper_kwh-x.lower_kwh)],stack:'band',symbol:'none',lineStyle:{opacity:0},areaStyle:{color:'#72b891',opacity:.24},tooltip:{valueFormatter:()=> '详见每小时区间表'}},
 {name:'85% 容量阈值',type:'line',yAxisIndex:1,data:labels.map(()=>threshold),lineStyle:{type:'dashed',color:'#bd6064'},itemStyle:{color:'#bd6064'},symbol:'none'}]});
 $('capacity-title').textContent='占用与峰值预警';$('capacity-legend').textContent='真实枪数/额定功率 + 模型负荷派生';
 table('forecast-table',['时间','电量','区间','空闲','排队','预警'],points.map(x=>[x.time.slice(11,16),fmt(x.load_kwh),fmt(x.lower_kwh)+'–'+fmt(x.upper_kwh),x.idle,x.queue,x.alert==='peak'?'峰值':'正常']));
 const peak=points.reduce((a,b)=>a.load_kwh>b.load_kwh?a:b),valley=points.reduce((a,b)=>a.load_kwh<b.load_kwh?a:b);$('forecast-advice').textContent=`当前窗口峰值 ${peak.time.slice(11,16)}（${fmt(peak.load_kwh)} kWh），低谷 ${valley.time.slice(11,16)}（${fmt(valley.load_kwh)} kWh）。${points.some(x=>x.alert==='peak')?'建议提前检查可用设备，并将可延迟订单引导至低谷时段。':'当前窗口未触发容量阈值预警，可优先推荐空闲率较高站点。'} 峰谷差 ${fmt(peak.load_kwh-valley.load_kwh)} kWh；空闲和排队由真实枪数、额定功率及预测负荷换算。`;
 const importance=Object.entries(d.feature_importance||{}).sort((a,b)=>b[1]-a[1]).slice(0,6);
 $('feature-explanation').innerHTML=`${esc(d.exogenous)}<br>${direct?'当前 H'+horizon+' 采用 '+esc(names[model])+'；CNN 学习可用周同期基线残差，GBT 使用站点级目标。':d.model==='station'?'分站 GBT 重要特征：'+importance.map(([k,v])=>esc(k)+' '+pct(v)).join(' · '):'当前采用 '+esc(names[d.model])+'。'}<br>${esc(d.interval_method)}`;
 const backtest=d.recent_backtest||[];chart('backtest-chart',{...axes(backtest.map(x=>x.time.slice(5,10))),grid:{left:32,right:5,top:12,bottom:17},xAxis:{type:'category',data:backtest.map(x=>x.time.slice(5,10)),axisLabel:{fontSize:8,interval:23}},yAxis:{type:'value',axisLabel:{fontSize:8},splitLine:{show:false}},series:[{name:'实际',type:'line',symbol:'none',data:backtest.map(x=>x.actual_kwh)},{name:'预测',type:'line',symbol:'none',data:backtest.map(x=>x.predicted_kwh),lineStyle:{type:'dashed'}}]});
 $('baseline-explanation').textContent=direct?`H${horizon} 验证集选模型；可用周同期基线测试 MAE ${fmt(direct.baseline_metrics.mae)} kWh，测试集不参与选择。`:`最佳基线 ${names[d.baseline]}，测试 MAE ${fmt(d.baseline_metrics.mae)} kWh。`;
 const rec=payload['load-forecast'].data.map(s=>{const ps=projectedPoints(s,horizon),idle=ps.filter(x=>x.idle!==null),avgIdle=idle.length?idle.reduce((a,x)=>a+x.idle,0)/idle.length:null,maxQueue=Math.max(...ps.map(x=>x.queue||0)),alerts=ps.filter(x=>x.alert==='peak').length;return {...s,avgIdle,maxQueue,alerts,score:(avgIdle??-99)-maxQueue*3-alerts*2}}).sort((a,b)=>b.score-a.score).slice(0,4);
 $('recommendation-title').textContent='低拥堵站点推荐';$('recommendation-legend').textContent='真实设备容量 + 同一预测窗口';table('forecast-recommendations',['站点','平均空闲','排队','预警'],rec.map(x=>[x.name,fmt(x.avgIdle,1),fmt(x.maxQueue,0),x.alerts]));}
function users(){const d=payload['user-demand'].data,t=d.evaluation.test.time[d.time_model],e=d.evaluation.test.energy[d.energy_model],available=d.user_count>0,simulated=d.data_source?.includes('模拟');$('user-title').textContent=simulated?'用户充电需求预测':available?'理解充电节奏':'用户预测：源数据未提供';$('user-badge').textContent=simulated?'':'只展示群体聚合 · 无用户明细';kpis('user-kpis',available?[
['覆盖用户',fmt(d.user_count,0),'全部输出，含冷启动回退'],['时段 HitRate@3',pct(t.hit_rate_3),names[d.time_model]],['时段 MRR',fmt(t.mrr,3),'每用户最后一次为测试'],['电量 MAE',fmt(e.mae)+' kWh',names[d.energy_model]],['预计平均电量',fmt(d.mean_next_kwh)+' kWh','群体统计'],['服务覆盖率',pct(d.coverage),'新用户只展示群体分布']]:
[['用户标识','未提供','官方源无用户 ID'],['时段预测','未训练','无法构造用户序列'],['电量预测','未训练','无法进行个人化评估'],['用户明细','未使用','不伪造用户数据'],['覆盖率','0%','字段缺失'],['处置','明确缺失','保留真实数据口径']]);
 chart('heatmap-chart',{tooltip:{position:'top',formatter:p=>`周${['一','二','三','四','五','六','日'][p.value[1]]} ${p.value[0]} 时<br>训练会话 ${p.value[2]} 次`},grid:{left:45,right:15,top:15,bottom:60},xAxis:{type:'category',data:Array.from({length:24},(_,i)=>i+'时'),splitArea:{show:true},axisLabel:{fontSize:10}},yAxis:{type:'category',data:['周一','周二','周三','周四','周五','周六','周日'],splitArea:{show:true}},visualMap:{min:0,max:Math.max(1,...d.heatmap.map(x=>x[2])),calculable:d.user_count>0,orient:'horizontal',left:'center',bottom:0,inRange:{color:['#edf5ed','#8bbfa0','#157d54']}},series:[{type:'heatmap',data:d.heatmap,itemStyle:{borderWidth:2,borderColor:'#fff'}}]});
 const demand=Object.entries(d.next_day_distribution).sort((a,b)=>a[0].localeCompare(b[0]));chart('next-demand-chart',{...axes(demand.map(x=>x[0].slice(5))),grid:{left:38,right:8,top:8,bottom:24},xAxis:{type:'category',data:demand.map(x=>x[0].slice(5)),axisLabel:{fontSize:9}},series:[{name:'预计用户',type:'bar',data:demand.map(x=>x[1]),barMaxWidth:28,itemStyle:{borderRadius:[4,4,0,0]}}]});
 chart('energy-chart',{...axes(d.energy_distribution.map(x=>fmt(x.from,0)+'–'+fmt(x.to,0))),grid:{left:38,right:8,top:8,bottom:28},xAxis:{type:'category',data:d.energy_distribution.map(x=>fmt(x.from,0)+'–'+fmt(x.to,0)),axisLabel:{fontSize:8,interval:1}},series:[{name:'用户数',type:'bar',data:d.energy_distribution.map(x=>x.count),itemStyle:{borderRadius:[4,4,0,0]}}]});
 table('user-evaluation',['任务 / 模型','HitRate@1','HitRate@3','MRR','MAE / kWh'],[...Object.entries(d.evaluation.test.time).map(([k,m])=>['时段 / '+names[k],pct(m.hit_rate_1),pct(m.hit_rate_3),fmt(m.mrr,3),'—']),...Object.entries(d.evaluation.test.energy).map(([k,m])=>['电量 / '+names[k],'—','—','—',fmt(m.mae)])]);
 $('user-fallback').textContent='';
 const segments=payload.overview.data.user_segments||[];$('user-segments').innerHTML=segments.map(x=>`<div class="segment"><b>${esc(fmt(x.users,0))} 人</b>${esc(x.segment)}<br>均量 ${esc(fmt(x.avg_kwh))} kWh</div>`).join('');}
function health(){const d=payload['pipeline-health'].data,q=payload['data-quality'].data,f=payload['load-forecast'].data;kpis('health-kpis',[
['源数据行数',fmt(d.source_manifest.reduce((a,x)=>a+x.rows,0),0),d.source_manifest.length+' 个官方数据源 · 校验和可追溯'],['质量规则',fmt(d.quality_rule_count,0),'ERROR / WARN / INFO'],['错误规则命中',fmt(d.error_rule_hits,0),'错误行隔离，不静默丢弃'],['预测站点',fmt(d.model_count,0),'每站未来 24 点'],['基线回退',fmt(d.baseline_fallbacks,0),'验证集选模'],['测试退化站点',fmt(d.test_degraded_count,0),'测试集只报告']]);
 $('storage-label').textContent=d.storage.startsWith('hdfs:')?'HDFS 存储':'本地 Spark 验证环境';$('layers').innerHTML=Object.entries(d.layers).map(([k,v])=>`<div class="layer"><b>${esc(k.toUpperCase())}</b><small>${esc(v)}</small></div>`).join('');
 const qualityScore=ids=>{const rows=q.filter(x=>ids.includes(x.rule_id));return rows.length?Math.max(0,100-Math.max(...rows.map(x=>x.failed_rate))*100):100},radar=[['完整性',qualityScore(['required','missing_grid','invalid_timestamp'])],['唯一性',qualityScore(['duplicate'])],['有效性',qualityScore(['station_domain','weather_domain','session_domain','snapshot_domain','bms_range','invalid_energy'])],['一致性',qualityScore(['foreign_key','dimension_mismatch','duration','weekday','weekday_onehot','capacity_conflict','invalid_duration','invalid_charging_time'])],['时序性',qualityScore(['missing_grid','soc_decrease','invalid_timestamp'])],['可追溯',d.source_manifest.length>0?100:0]];
 chart('quality-radar-chart',{radar:{radius:'64%',indicator:radar.map(x=>({name:x[0],max:100})),axisName:{fontSize:8,color:'#71847b'},splitNumber:3},series:[{type:'radar',symbolSize:3,areaStyle:{opacity:.2},data:[{value:radar.map(x=>x[1])}]}]});
 const severity={BLOCKER:0,ERROR:1,WARN:2,INFO:3};table('quality-table',['表 / 规则','等级','异常数','处置'],[...q].sort((a,b)=>b.failed_count-a.failed_count||severity[a.severity]-severity[b.severity]).map(x=>[x.table_name+' / '+x.rule_id,x.severity,fmt(x.failed_count,0),x.action]));
 table('pipeline-table',['作业','状态','Application ID'],d.stages.map(x=>[x.stage,x.status,x.application_id]));
 table('model-table',['站点','小时模型','H24 直接模型','H24 MAE','改善','状态','模型版本'],f.map(x=>{const h=x.direct_horizons?.['24'];return [x.name,names[x.model],h?names[h.model]:'—',fmt(h?.metrics?.mae),pct(h?.improvement),x.test_degraded?'测试退化':(h?.model||x.model)==='8week'?'基线回退':'已发布',x.model_version]}));}
function render(){if(!payload)return;$('empty').classList.add('hidden');document.querySelectorAll('.view').forEach(s=>s.classList.toggle('active',s.id==='view-'+view));({overview,forecast,users,health})[view]();}
function switchView(name){view=name;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view)});document.querySelectorAll('.view').forEach(s=>s.classList.toggle('active',s.id==='view-'+view));render();}
function status(message,kind='warn'){$('status').className='status '+kind;$('status-text').textContent=message;}
async function getJSON(url){const res=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!res.ok)throw new Error('HTTP '+res.status);return res.json()}
async function load(){try{if(location.protocol==='file:')throw new Error('请通过 HTTP 打开大屏');let current,staticFallback=false;try{current=await getJSON('data/current.json')}catch(_){staticFallback=true;current={files:Object.fromEntries(['overview','stations','station-ranking','load-forecast','user-demand','data-quality','pipeline-health'].map(k=>[k,k+'.json']))}}const entries=await Promise.all(Object.entries(current.files).map(async([k,p])=>[k,await getJSON('data/'+p)]));const candidate=Object.fromEntries(entries);if(staticFallback)current.runId=candidate.overview?.runId;const nature=candidate.overview?.dataNature;for(const key of ['overview','stations','station-ranking','load-forecast','user-demand','data-quality','pipeline-health']){const v=candidate[key];if(!v||v.schemaVersion!=='1.0'||v.runId!==current.runId||v.dataNature!==nature||!['模拟数据','真实数据','真实数据+模拟补齐'].includes(v.dataNature))throw new Error('数据契约或运行编号不一致')}
 payload=candidate;lastLoad=Date.now();const meta=payload.overview,real=meta.dataNature!=='模拟数据',hybrid=meta.dataNature==='真实数据+模拟补齐';$('data-time').textContent='数据截止 '+meta.dataTime;$('generation').textContent='生成 '+meta.generatedAt+' · 运行 '+meta.runId;$('data-badge').textContent=hybrid?'北京 · 真实交易 / 模拟补齐':real?'真实数据':'北京 · 模拟数据';$('brand-subtitle').textContent=real?'BEIJING REAL CHARGING INTELLIGENCE':'BEIJING CHARGING INTELLIGENCE';$('data-disclaimer').textContent='';$('nav-map').classList.remove('hidden');$('real-map-note').classList.add('hidden');$('map-legend').textContent=real?'导航沿用程序内置北京地图；公开站点仅提供匿名 1km 网格，不伪造精确点位。':'数据集无精确经纬度，模拟数据按行政区统计。';
 const select=$('station-select');select.innerHTML=payload['load-forecast'].data.map(x=>`<option value="${x.station_id}">${esc(x.name)}</option>`).join('');
 const age=Date.now()-Date.parse(meta.generatedAt);status(age>86400000?'结果已延迟：保留最近一次成功结果。':(hybrid?'北京真实交易 · Spark GBT / CNN 残差训练成功 · 缺失域已模拟补齐':real?'真实历史数据 · Spark/CNN 计算成功':'历史模拟数据回放 · 最近一次计算成功'),age>86400000?'warn':'');

 if(payload['pipeline-health'].data.status!=='SUCCESS')status('链路已降级：展示最近一次可用结果。','warn');
 try{const attempt=await getJSON('data/latest-attempt.json');if(attempt.status==='FAILED'&&Date.parse(attempt.generatedAt)>Date.parse(meta.generatedAt))status('最新任务失败：'+attempt.stage+'；保留上次成功结果。','error')}catch(_){}
 render();}catch(e){status((payload?'已降级，保留已加载结果：':'数据暂不可用：')+e.message,'error');if(!payload){$('empty').classList.remove('hidden');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));}}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$('station-select').addEventListener('change',e=>{selected=Number(e.target.value);forecast()});document.querySelectorAll('[data-h]').forEach(b=>b.addEventListener('click',()=>{horizon=Number(b.dataset.h);document.querySelectorAll('[data-h]').forEach(x=>x.classList.toggle('active',x===b));if(payload)forecast()}));$('refresh').addEventListener('click',load);window.addEventListener('resize',()=>charts.forEach(c=>c.resize()));setInterval(()=>{if(lastLoad&&Date.now()-lastLoad>300000)status('连接已延迟，保留最近一次成功结果。','warn')},60000);setInterval(load,120000);startParticles();load();
